Feature/profile
Kovallll/twitter pull request #2
Opened 2024-10-09 06:15 UTC by Kovallll

Добавил профиль, возможность изменить данные профиля, sidebar с навигацией,, но ещё пока без самой навигации, также есть возможность добавить твит в модальном окне и выйти их аккаунта, создание твитов, картинки загружаю в firestorage, переключатель темы, но пока ещё темы нету, sidebar с поиском, картинками твитов и аккаунтами пользователей,при поиске ищет совпадение в тексте всех твитов и при нажатии переходи на страницу с твитом. картинки просто загружаю из твитов и там отображаю, в блоке аккаунта можно подписаться/отписаться от пользователя. Таска: https://app.clickup.com/t/8695xx8r1, Коммит: 3704c6ddcccdabf289658cea4d2a4c4b67ff0f9b

2024-10-10 10:13 UTC, anyaprystavka requested changes

2024-10-10 10:13 UTC, anyaprystavka commented on declare.d.ts
>  }
тут файл лучше перенести в папку types
чтобы он хранился вместе с типами

2024-10-10 10:13 UTC, anyaprystavka commented on package.json
> +        "axios": "^1.7.7",
dependencies

2024-10-10 10:13 UTC, anyaprystavka commented on package.json
> +        "uuid": "^10.0.0",
dependencies

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/EditProfileModal/index.tsx
> +    return (
<img width="594" alt="Снимок экрана 2024-10-09 в 12 05 42" src="https://github.com/user-attachments/assets/9361d137-cb59-498f-b8a6-f83e19e4334d">
модальное окно прижато вверху экрана и не весь блок виден

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/EditProfileModal/styled.ts
> +                padding: ${theme.spaces.sm + 'px'} ${theme.spaces.sm + 'px'};
можно тут просто
padding: ${theme.spaces.sm + 'px'};

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/EditProfileModal/index.tsx
> +                    $backgroundColor={theme.palette.blue}
когда пользователь сохранил данные о себе(притом что-то поменял)
потом высвечивать тост "data saved successfully"

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/EditProfileModal/index.tsx
> +                    <Text>{descriptionText}</Text>
при заполнении поля description (оно изначально было пустое)
после сохранения данных - верстка не статичная и видно, что при добавлении описания верстка едет вниз
предлагаю сделать ее статичной и может уже писать какую-то информацию(если под не заполнены)

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/Loader/styles.ts
> +                display: flex;
пустая строка

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/Loader/index.tsx
> +export const HeaderLoader = () => {
этот компонент переиспользуется
его лучше вынести в папку ui, например
там будут переиспользуемые компоненты

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +    const { user } = useAppSelector((state) => state.user)
передаваемые функции в useSelector переиспользуются
можно вынести в папке store => selector эти функции

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +    const { isLoadingInitialData } = useAppSelector((state) => state.boolean)
тут где ты берешь переменную boolean
лучше переименовать на что-то более информативное
дополнить название

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +                    {title ? (
терновники чуть ухудшают читаемость
тут предлагаю вынести что-то в отдельный компонент или в react элемент в этом компоненте

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +                                    src={user.avatar.url}
дублирование есть в коде - user.avatar.url

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +                                <HeaderTitle>{user?.name}</HeaderTitle>
а если не будет информации об имени
что будет отображаться?

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Header/styled.ts
> +            ${mixins.flexRowSB}
не используется тег header

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/EditProfileModal/styled.ts
> +    ${({ theme }) => {
в мобильной версии модальное окно прижато к левому и правому краю
тут лучше сделать отступы и сверху чуть сделать отступ

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/styled.ts
> +            font-size: ${theme.fontSizes.xs + 'px'};
пустая строка

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/config.ts
> +export const logoAltText = 'logo'
в мобильной версии при закрытии сайдбара с навигацией отображается все корректно
потом при переходе в обычное разрешение экрана и при этом открыты dev tools
не отображается сайдбар

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Modal/ConfirmModal/index.tsx
> +    onConfirm,
в текущем пр где-то деструктуризируешь в самом компоненте
когда приходят три пропса
тут иначе
стоит придерживатьсяединого стиля

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Modal/ConfirmModal/styled.ts
> +export const Buttons = styled.div`
ButtonsWrap

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Modal/ConfirmModal/index.tsx
> +                <Button onClick={onConfirm}>{confirmText}</Button>
стоит добавить фон кнопкам
чтобы не был просто текст на белом фоне

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
> +    }, [dispatch, user.userId])
dispatch тут про него пишут, что нормально использовать
https://qna.habr.com/q/984487

на практике было много ошибок,  связанных с этим
не рекомендовала бы его использовать везде в качестве deps

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +import { Logo } from '@styles/global'
используй в styles файл для re export
чтобы уменьшить ко-во импортов

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +    if (window.innerWidth >= hiddenSidebarWidth && !isSidebarOpen) {
кастомный хук
https://my-js.org/docs/cheatsheet/custom-hooks/#usewindowsize

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +                        {sidebarLinks.map((link, index) => (
деструктуризация

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +                                <Icon src={link.icon} alt={navIconAltText} />
в качестве ключа можно link использовать

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/styled.ts
> +            'px ' +
форматирование

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/styled.ts
> +            }
пустая строка

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/styled.ts
> +                margin-bottom: ${theme.spaces.md + 'px'};
пустая строка

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/TweetImage/index.tsx
> +    return (
при добавлении фотографии в твит
нельзя выложить только фотографию
и кнопка tweet не активна
а что в итоге нужно поправить? это пользователю нужно сообщить

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/TweetImage/index.tsx
> +                alt={closeIconAltText}
картинка не подгрузилась при создании твита
https://images.pexels.com/photos/2486168/pexels-photo-2486168.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/TweetImage/index.tsx
> +                alt={closeIconAltText}
только при перегрузке страницы появилась в созданном твите

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/index.tsx
> +    isUserTweet = false,
деструктуризация внутри компонента

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/index.tsx
> +        clickLikeTweet(user, tweetId, isLiked, dispatch)
при долгом клике он насчитал 5 лайков
баг

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TweetCreator/index.tsx
> +        setCreatedTweetImages((prev) => prev!.filter((file) => file.id !== id))
тут ругается,  что нет ничего в стейте? можно if явно использовать
чтобы ! не пропустить

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TweetCreator/index.tsx
> +            id: id ?? '',
тут id точно должен приходить по идее
так как uuid используешь

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/index.tsx
> +                data.map((item) => item)
key

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/styled.ts
> +            background-color: #eff3f4;
из темы

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/styled.ts
> +export const PupupText = styled.div`
нейминг?

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/styled.ts
> +export const PupupText = styled.div`
почему это div?

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/SearchBlock/Search/index.tsx
> +    placeholder = 'search',
предлагаю в самом поле написать поиск чего происходит
без добавления для этого PopUp для отображения того
что поиск по по твитам и юзерам

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/SearchBlock/index.tsx
> +    const [isSearch, setIsSeacrh] = useState(false)
поиск в итоге по юзерам и твитам совмещен ? там немного по-другому в тз

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/TweetImageBoard/index.tsx
> +                    {tweetsImages?.slice(0, countTweetsImages).map((image) => (
тут отдельно стоит вынести в переменную выше преобразование массива и обернуть в useMemo
чтобы данные пересчитывали только тогда
когда это необходимо

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/TweetImageBoard/index.tsx
> +                            <Image src={image.url} alt={imageAltText} />
деструктуризация

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/TwitterAccountsBoard/index.tsx
> +                        {accounts.map((account) => (
деструктуризация

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TwitterUsersContent/TwitterAccountsBoard/index.tsx
> +                                        account.userId!
почему as?

2024-10-10 10:13 UTC, anyaprystavka commented on src/constants/index.tsx
> +export const milliSeconds = 1000
файл только расширяется
чтоит разделить файл на несколько по смыслу

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TweetCreator/FilesUploader/index.tsx
> +                const file = files[i]
стоит добавить валидацию на вес изображения


handleFileChange = (event) => {
    const file = event.target.files[0];
    
    if (file.size > 1048576) { // 1 MB in bytes
      alert('File size exceeds 1 MB. Please choose a smaller file.');
      event.target.value = ''; // clear the file input
    } else {
      // Handle the file upload logic here
    }
  };

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/TweetCreator/FilesUploader/index.tsx
> +                const file = files[i]
только в байтах
тут массив представлен

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/index.tsx
> +import { clickLikeTweet, dowloadImagesFromStorage } from '@firebase'
при добавлении картинки в твите
на странице пользователя сразу был поставлен лайк
но количество лайков было 0

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Tweet/index.tsx
> +import { clickLikeTweet, dowloadImagesFromStorage } from '@firebase'
<img width="654" alt="Снимок экрана 2024-10-09 в 14 31 15" src="https://github.com/user-attachments/assets/b0e34f13-cac1-40ce-982d-fcdd4034320c">

2024-10-10 10:13 UTC, anyaprystavka commented on src/pages/Login/index.tsx
> +    }, [dispatch, text])
не советовала бы использовать dispatch в deps
где-то пишут, что ссылка нестабильная
где-то в источниках, что стабильная

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/index.tsx
>      const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
useMemo
когда работаем с библиотечным функциями, желательно их оборачивать, так как под капотом они могут выполнять сложную логику
https://github.dev/react-hook-form/react-hook-form/tree/master/src

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/index.tsx
> +    const letterCountText = value.length + slashText + maxLength
работа с конкатенацией
`
const letterCountText = `${value.length} / ${maxLength}` 
`

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/index.tsx
>          const { value } = e.target
onChangeInput(e.target.value)

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/index.tsx
> +            {!!register && <ErrorText role="alert">{error}</ErrorText>}
по идее тут должен быть error
register первоначально сбил с толку
`            {!!error && <ErrorText role="alert">{error}</ErrorText>}
`

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/index.tsx
> +        label,
тут должен быть не label
а name

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/index.tsx
> +        label,
также типизацию нужно поменять
 name?: Path<T> | string

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +    const [isShow, setIsShow] = useState(false)
isShow что?

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +import { useState } from 'react'
везде нужно пересмотреть работу с формами
register передается на несколько уровней
существуют более удобные способы работы с react-hook-form
в документации представлены и другие примеры


 https://react-hook-form.com/docs/useformcontext

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +import { FieldValues, Path } from 'react-hook-form'
нужно убрать везде логику по хранению значений полей в redux

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +    const passwordLabel = label ? label : ('password' as Path<T>)
сразу можно написать 
label || 'password'

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +                label={passwordLabel}
label || 'password'


тут не должен быть name, вместо label?

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +                type={type}
type = {isShow ? 'text' : 'password'}

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +    const eyeIcon = isShow ? images.eyeSlash : images.eyeSee
нейминг
eye see  -> open eye

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
>  export function RequireAuth({ children, redirectTo }: PathProps) {
нейминг
ProtectedRoute

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
>  export function AuthenticatedProtect({ children, redirectTo }: PathProps) {
нейминг
UnauthorizedRoute

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
> +    const tokens = JSON.parse(localStorage.getItem(tokensLocalStorage))
нейминг - а сколько в итоге токенов? 1? 2? 3?

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
> +    const tokens = JSON.parse(localStorage.getItem(tokensLocalStorage))
также parse и stringily медленный операции
тут лучше обернуть все в useMemo

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
> +        setPrevSearchValue(searchValue)
если я тут буду обращаться к предыдущему значению
то мне нужно писать prevPrevSearchVAlue?
нужно подправить нейминг(состояние)

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/ProtectedPaths/index.tsx
> +    const dispatch = useAppDispatch()
тут для работы роуминга будет достаточно использовать переменную user по идее
для чего тут код с 16 по 34 строки?

2024-10-10 10:13 UTC, anyaprystavka commented on src/pages/Login/index.tsx
> +import { PasswordInput } from '@components/Input/PasswordInput'
Зачем нужна форма, если ты используешь redux или наоборот?

2024-10-10 10:13 UTC, anyaprystavka commented on src/pages/TweetPage/index.tsx
> +    const tweetData = accounts
useMemo
операции в лучшем случае будут иметь сложность O(n2)

2024-10-10 10:13 UTC, anyaprystavka commented on src/utils/index.tsx
> +
1) тут можно реализовать паттерн Singleton
2) Что делать, если локальное хранилище будет недоступно? как с этим справиться?

3) Вместо [string](key: string,) нужно указать явно что мы можем передавать(в set и GetStaticPaths)
4)для чего используется JSON.stringify в get?
5) Зачем выполнять Stringify в get? нужна типизация
6) Что такое undefinedItem. если у нас нет ничего в локальном хранилище, мы должны получить undefined

7)для чего нужно использовать JSON.stringify(value)?

2024-10-10 10:13 UTC, anyaprystavka commented on src/styles/global.ts
> +            background: white;
цвета объявлены не в едином формате

2024-10-10 10:13 UTC, anyaprystavka commented on src/styles/theme.ts
> +        successColor: '#6EC207',
у тебя цвета могут использовать не только, например, для border, но и в других случаях
тут предлагаю просто явно задать цвет
white, green, red, lightGrey и тд

2024-10-10 10:13 UTC, anyaprystavka commented on storage.rules
> +}
отсутствует пустая строка

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +import { useState } from 'react'
использовать также useForm

контроллеры
https://react-hook-form.com/docs/usecontroller/controller

2024-10-10 10:13 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +} from './config'
Желательно сделать подсветку актуальной страницы в Sidebar

2024-10-10 10:13 UTC, anyaprystavka commented on src/pages/Profile/index.tsx
> +            <Sidebar />
пересмотри перезагрузку страниц и переход по страницам
404 ошибка

2024-10-10 11:28 UTC, Kovallll commented on declare.d.ts
>  }
поправил

2024-10-10 11:29 UTC, Kovallll commented on package.json
> +        "axios": "^1.7.7",
поправил

2024-10-10 11:29 UTC, Kovallll commented on package.json
> +        "uuid": "^10.0.0",
поправил

2024-10-10 11:29 UTC, Kovallll commented on src/components/EditProfileModal/index.tsx
> +    return (
поправил

2024-10-10 11:34 UTC, Kovallll commented on src/components/EditProfileModal/styled.ts
> +                padding: ${theme.spaces.sm + 'px'} ${theme.spaces.sm + 'px'};
поправил

2024-10-10 11:39 UTC, Kovallll commented on src/components/EditProfileModal/index.tsx
> +                    $backgroundColor={theme.palette.blue}
поправил

2024-10-10 12:10 UTC, Kovallll commented on src/components/EditProfileModal/index.tsx
> +                    <Text>{descriptionText}</Text>
поправил

2024-10-10 12:17 UTC, Kovallll commented on src/components/Header/Loader/styles.ts
> +                display: flex;
поправил

2024-10-10 12:17 UTC, Kovallll commented on src/components/Header/Loader/index.tsx
> +export const HeaderLoader = () => {
вроде нет, он используется только в Header компоненте

2024-10-10 12:42 UTC, Kovallll commented on src/components/Header/index.tsx
> +    const { user } = useAppSelector((state) => state.user)
добавил

2024-10-10 12:43 UTC, Kovallll commented on src/components/Header/index.tsx
> +    const { isLoadingInitialData } = useAppSelector((state) => state.boolean)
поправил

2024-10-10 12:52 UTC, Kovallll commented on src/components/Header/index.tsx
> +                    {title ? (
поправил

2024-10-10 12:54 UTC, Kovallll commented on src/components/Header/index.tsx
> +                                    src={user.avatar.url}
поправил

2024-10-10 12:55 UTC, Kovallll commented on src/components/Header/index.tsx
> +                                <HeaderTitle>{user?.name}</HeaderTitle>
обсудили, тут она будет, мой косяк, убрал проверку

2024-10-10 12:55 UTC, Kovallll commented on src/components/Header/styled.ts
> +            ${mixins.flexRowSB}
поправил

2024-10-10 13:04 UTC, Kovallll commented on src/components/EditProfileModal/styled.ts
> +    ${({ theme }) => {
ну на мобилку я ориентировался на размер 370px а сама модалка 340, поэтому было норм, ну я уменьшил до 320 размер модалки, чтобы был побольше запас

2024-10-10 13:06 UTC, Kovallll commented on src/components/Input/styled.ts
> +            font-size: ${theme.fontSizes.xs + 'px'};
поправил

2024-10-10 13:09 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +    if (window.innerWidth >= hiddenSidebarWidth && !isSidebarOpen) {
спасибо, добавил

2024-10-10 13:10 UTC, Kovallll commented on src/components/Sidebar/config.ts
> +export const logoAltText = 'logo'
поправил

2024-10-10 13:12 UTC, Kovallll commented on src/components/Modal/ConfirmModal/index.tsx
> +    onConfirm,
поправил

2024-10-10 13:13 UTC, Kovallll commented on src/components/Modal/ConfirmModal/styled.ts
> +export const Buttons = styled.div`
поправил

2024-10-10 13:29 UTC, Kovallll commented on src/components/Modal/ConfirmModal/index.tsx
> +                <Button onClick={onConfirm}>{confirmText}</Button>
поправил

2024-10-10 13:59 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +                        {sidebarLinks.map((link, index) => (
поправил

2024-10-10 14:35 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +                                <Icon src={link.icon} alt={navIconAltText} />
поправил

2024-10-10 14:48 UTC, Kovallll commented on src/components/Sidebar/styled.ts
> +            'px ' +
поправил

2024-10-10 14:49 UTC, Kovallll commented on src/components/Sidebar/styled.ts
> +            }
поправил

2024-10-10 14:49 UTC, Kovallll commented on src/components/Sidebar/styled.ts
> +                margin-bottom: ${theme.spaces.md + 'px'};
поправил

2024-10-10 15:03 UTC, Kovallll commented on src/components/Tweet/TweetImage/index.tsx
> +    return (
поправил

2024-10-10 15:05 UTC, Kovallll commented on src/components/Tweet/TweetImage/index.tsx
> +                alt={closeIconAltText}
странно, не знаю почему так, у меня она грузиться нормально

2024-10-10 15:12 UTC, Kovallll commented on src/components/Tweet/index.tsx
> +    isUserTweet = false,
поправил

2024-10-10 15:15 UTC, Kovallll commented on src/components/Tweet/index.tsx
> +        clickLikeTweet(user, tweetId, isLiked, dispatch)
изначально я заметил баг при быстром клике начислялись лишние лайки и я добавил debounce чтобы это пофиксить, но если кликать в определенном темпе, чуть реже, чем задержка, то да, также добавляются, я решил чекнуть как в твиттере, у них на самом деле также, если кликать быстро, то будут собираться лишние лайки, но при обновлении они сбрасываются, я сделал также, просто оставляю уникальные значения в массиве

2024-10-10 15:17 UTC, Kovallll commented on src/components/TweetCreator/index.tsx
> +        setCreatedTweetImages((prev) => prev!.filter((file) => file.id !== id))
поправил

2024-10-10 15:35 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +import { Logo } from '@styles/global'
поправил

2024-10-10 15:37 UTC, Kovallll commented on src/components/TweetCreator/index.tsx
> +            id: id ?? '',
поправил

2024-10-10 15:39 UTC, Kovallll commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/index.tsx
> +                data.map((item) => item)
добавил ключ при создании data в getTweetsTexts

2024-10-10 15:40 UTC, Kovallll commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/styled.ts
> +            background-color: #eff3f4;
поправил

2024-10-10 15:41 UTC, Kovallll commented on src/components/TwitterUsersContent/SearchBlock/SearchPopup/styled.ts
> +export const PupupText = styled.div`
поправил

2024-10-10 15:54 UTC, Kovallll commented on src/components/TwitterUsersContent/SearchBlock/Search/index.tsx
> +    placeholder = 'search',
поправил

2024-10-10 15:57 UTC, Kovallll commented on src/components/TwitterUsersContent/SearchBlock/index.tsx
> +    const [isSearch, setIsSeacrh] = useState(false)
тут пока только по твитам, на странице profile я инициализирую data как массив элементов с текстом твитов, на других буду передавать юзеров, просто пока только страница профиль и поэтому тут только твиты

2024-10-10 16:03 UTC, Kovallll commented on src/components/TwitterUsersContent/TweetImageBoard/index.tsx
> +                            <Image src={image.url} alt={imageAltText} />
поправил

2024-10-10 16:09 UTC, Kovallll commented on src/components/TwitterUsersContent/TweetImageBoard/index.tsx
> +                    {tweetsImages?.slice(0, countTweetsImages).map((image) => (
поправил

2024-10-10 16:17 UTC, Kovallll commented on src/components/TwitterUsersContent/TwitterAccountsBoard/index.tsx
> +                        {accounts.map((account) => (
добавил

2024-10-10 16:17 UTC, Kovallll commented on src/components/TwitterUsersContent/TwitterAccountsBoard/index.tsx
> +                                        account.userId!
убрал

2024-10-10 16:23 UTC, Kovallll commented on src/constants/index.tsx
> +export const milliSeconds = 1000
поправил

2024-10-10 16:25 UTC, Kovallll commented on src/components/TweetCreator/FilesUploader/index.tsx
> +                const file = files[i]
я делал валидацию на вес изображения, писал file.size <= maxUploadSizeImage, только вот не уверен на счет как раз размера картинки, я поставил 40мб, не знаю не многовато ли

2024-10-10 16:33 UTC, Kovallll commented on src/components/Tweet/index.tsx
> +import { clickLikeTweet, dowloadImagesFromStorage } from '@firebase'
поправил

2024-10-10 16:33 UTC, Kovallll commented on src/pages/Login/index.tsx
> +    }, [dispatch, text])
пока оставлю, если будут баги, уберу

2024-10-10 16:34 UTC, Kovallll commented on src/components/ProtectedPaths/index.tsx
> +    }, [dispatch, user.userId])
пока оставлю, если будут баги, уберу

2024-10-10 16:36 UTC, Kovallll commented on src/components/Input/index.tsx
> +    const letterCountText = value.length + slashText + maxLength
поправил

2024-10-10 16:39 UTC, Kovallll commented on src/components/Input/index.tsx
>      const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
поправил

2024-10-10 16:41 UTC, Kovallll commented on src/components/Input/index.tsx
>          const { value } = e.target
поправил

2024-10-10 16:44 UTC, Kovallll commented on src/components/Input/index.tsx
> +            {!!register && <ErrorText role="alert">{error}</ErrorText>}
не, просто мне нужно сразу иметь компонент ErrorText чтобы при появлении ошибки верстка не прыгала, тут я проверяю с помощью !!register есть ли валидации и нужно ли оставлять под ошибку место, если поставить !!error то ErrorText будет рендериться только когда ошибка есть, а изначально ее нет

2024-10-10 16:51 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +    const [isShow, setIsShow] = useState(false)
поправил

2024-10-10 19:09 UTC, Kovallll commented on src/components/Input/index.tsx
> +        label,
переписав без использования redux для формы я это совсем удалил

2024-10-10 19:09 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +import { useState } from 'react'
поправил

2024-10-10 19:09 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +import { FieldValues, Path } from 'react-hook-form'
убрал

2024-10-10 19:09 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +    const passwordLabel = label ? label : ('password' as Path<T>)
убрал

2024-10-10 19:09 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +                label={passwordLabel}
удалил

2024-10-10 19:12 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +                type={type}
немного не понял о чем ты, в переменной type у меня также и написано, ну и я вынес это в переменную, т.к. писать тернарное выражение в пропсах не очень хорошо читаемо

2024-10-10 19:13 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +    const eyeIcon = isShow ? images.eyeSlash : images.eyeSee
поправил

2024-10-10 19:14 UTC, Kovallll commented on src/components/ProtectedPaths/index.tsx
>  export function RequireAuth({ children, redirectTo }: PathProps) {
поправил

2024-10-10 19:14 UTC, Kovallll commented on src/components/ProtectedPaths/index.tsx
>  export function AuthenticatedProtect({ children, redirectTo }: PathProps) {
поправил

2024-10-10 19:23 UTC, Kovallll commented on src/pages/Login/index.tsx
> +import { PasswordInput } from '@components/Input/PasswordInput'
убрал

2024-10-10 19:27 UTC, Kovallll commented on src/components/ProtectedPaths/index.tsx
> +    const tokens = JSON.parse(localStorage.getItem(tokensLocalStorage))
поправил нейминг, parse перенес в LocalStorage

2024-10-10 19:32 UTC, Kovallll commented on src/components/ProtectedPaths/index.tsx
> +        setPrevSearchValue(searchValue)
не понят этот момент, в переменной prevSearchValue храниться предыдущее значение поиска, чтобы сравнивать изменился ли поиск и обновлять данные, как по мне нейминг нормальный и вполне соответствует хранимому значению

2024-10-10 19:58 UTC, Kovallll commented on src/components/ProtectedPaths/index.tsx
> +    const dispatch = useAppDispatch()
это был код по инициализации данных юзера, я его перенес в InitializerUserData компонент. По повоту роута, с user роут не получится, т.к. при обновлении страницы данные обнуляются до дефолтных и если привязыватся допустим к userId, то находясь на странице профиля и обновляя страницу будет следущее: данные обнуляются, меня редиректит на login, затем данные устанавливаются и опять редиректит на profile, поэтому так не получится.

2024-10-10 20:01 UTC, Kovallll commented on src/pages/TweetPage/index.tsx
> +    const tweetData = accounts
добавил

2024-10-10 20:23 UTC, Kovallll commented on src/utils/index.tsx
> +
1. реализовал, 2. добавил проверку на доступ. 3.key это всегда будет строка, это же ключ в localStorage, а value установил в unknown т.к. в lcSt можно установить что угодно. 4. я переписал get и теперь он парсит строку полученную из lcSt и возращает спаршеный элемент и теперь это может быть чем угодно, поэтому поставил unkown. 5.убрал, и возвращаю null если ничего нет, из lcSt возвращается, вроде, null, если ничего нет. 7. т.к.я могу попытаться установить объект в lcSt, а setItem принимает вторым аргументом только строку

2024-10-10 20:28 UTC, Kovallll commented on src/styles/theme.ts
> +        successColor: '#6EC207',
ну для базовых цветов, которых 1-2 оттенка, например синий, так можно сделать blue и lightBlue, но с тем же серым у меня 5 оттенков и будет путаница если их так называть, поэтому основные я назвал gray, lightGray, а специализированные, которые в основном предназначены для одного компонента и назвал в соответствии с ними, так легче понять что за цвет

2024-10-10 20:29 UTC, Kovallll commented on storage.rules
> +}
поправил

2024-10-10 20:50 UTC, Kovallll commented on src/styles/global.ts
> +            background: white;
поправил

2024-10-10 20:50 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +} from './config'
добавил

2024-10-10 20:52 UTC, Kovallll commented on src/pages/Profile/index.tsx
> +            <Sidebar />
404 отрабатывает, с перезагрузкой тоже проблем вроде нет

2024-10-11 13:22 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +                type={type}
поняла тут
оставим так, в целом как кому удобнее

2024-10-11 13:30 UTC, anyaprystavka commented on src/styles/theme.ts
> +        successColor: '#6EC207',
изначально не было основных цветов
поэтому так и могло произойти
иногда встречаются и разные вариации серого в теме

2024-10-11 13:32 UTC, anyaprystavka commented on src/pages/Profile/index.tsx
> +            <Sidebar />
были проблемы
сейчас вижу,  что работает все

но когда неверно URL введен
тут логичнее бы оставить навигацию или кнопку для возврата на главную страницу
не оставлять только белый экран

2024-10-11 13:33 UTC, anyaprystavka commented on src/components/EditProfileModal/styled.ts
> +    ${({ theme }) => {
сейчас корректно все

2024-10-11 13:33 UTC, anyaprystavka commented on src/components/TweetCreator/FilesUploader/index.tsx
> +                const file = files[i]
оптимально будет 10-15

2024-10-11 14:22 UTC, Kovallll commented on src/components/TweetCreator/FilesUploader/index.tsx
> +                const file = files[i]
хорошо, поставил 15мб

2024-10-11 14:29 UTC, Kovallll commented on src/styles/theme.ts
> +        successColor: '#6EC207',
хорошо, в ветке с темой пересмотрю ещё нейминг всех цветов

2024-10-11 14:40 UTC, Kovallll commented on src/pages/Profile/index.tsx
> +            <Sidebar />
добавил кнопку BackButton с возвратом назад по истории посещений

2024-10-13 12:05 UTC, anyaprystavka requested changes

2024-10-13 12:05 UTC, anyaprystavka commented on src/components/EditProfileModal/index.tsx
> +    nameText,
если открыть окно для того, чтобы поменять данные пользователя
и ничего не поменять, потом нажать на сохранение
то высветится уведомление об успешном обновлении данных

в данном случае предлагаю высвечивать другую информацию или дизейблить кнопку сохранения

2024-10-13 12:05 UTC, anyaprystavka commented on src/components/EditProfileModal/index.tsx
> +        dispatch(updateUserData({ ...editData, description: value }))
нигде не используется в приложении потом
description

2024-10-13 12:05 UTC, anyaprystavka commented on src/components/EditProfileModal/index.tsx
> +        dispatch(updateUserData({ ...editData, social: value }))
нигде не используется в приложении потом
social
нужно пересмотреть еще раз формы и использования данных в приложении

2024-10-13 12:05 UTC, anyaprystavka commented on src/utils/index.tsx
> +
2) В случае отсутсвия localStorage нужно как-то уведомить пользователя класса (например сделать throw new Error('localStorage не доступен'))
3) Без реализации третьего пункта нет никакого смысла в этом классе, тк ты никаким образом не улучшил стандартный (за исключением проверки его наличия) localStorage и в конечном итоге использование localStorage как window.localStorage.setItem(...) и window.localStorage.getItem(...) ничем не отличается от твоего варианта, тк ты не получаешь преимуществ typescript 
Пример (https://medium.com/@gcascio/how-to-add-types-to-your-local-storage-9e47ca0087af)
Таким образом ты сразу при вызове getItem будешь знать какой объект вернется или будет null
4) Здесь проблема что если ничего не найдено ты делаешь JSON.parse(JSON.strigify(null)), что аналогично просто возвращению null. Данная манипуляция является просто усложенением (плюс JSON parse и JSON stringify являются достаточно медленными функциями)


8) Почему такая реализация(checkIsLocalStorageAvailable)? Лучше проверить !window.localStorage -> throw new Error? Или в крайнем случае проверить что в window.localStorage есть все интересующие методы

9) Как доп улучшение можно добавить метод deleteItem и clearStorage

2024-10-13 12:05 UTC, anyaprystavka commented on src/constants/dynamicConstants/index.ts
> +import eyeOpen from '@assets/icons/eyeSee.svg'
название файла - константы не могут быть динамичные
лучше назвать defaultValue, например

2024-10-13 12:06 UTC, anyaprystavka commented on src/pages/Profile/index.tsx
> +            <Sidebar />
изменения подлиты удаленно?

2024-10-13 12:14 UTC, anyaprystavka requested changes

2024-10-13 12:14 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +                            <Logo src={logo} alt={logoAltText} />
пересмотри отображение иконки
<img width="284" alt="image" src="https://github.com/user-attachments/assets/e15895a0-a810-4611-8bd8-f024b858e0c0">

2024-10-13 12:14 UTC, anyaprystavka commented on src/constants/dynamicConstants/index.ts
> +    isLoadingTweet: false,
в итоге state.booleanStates не информативное название(когда обращаешься к стору)

также isSidebarOpen: false,
    isTweetModalOpen: false,
    
избыточно хранить в redux, так как встречается только один раз в приложении
лучше использовать состояние
    
    в итоге у тебя по неймингу останется loaderState, например
    так как хранится будет только
    isLoadingInitialData: false,
    isLoadingTweet: false,

2024-10-13 12:14 UTC, anyaprystavka commented on src/components/Modal/ConfirmModal/index.tsx
> +import { cancelText, checkTitleText } from './config'
в этом окне нужно добавить cursor pointer на кнопки
чтобы кнопка "Log out" все же выделялась, стоит подсветить ее другие цветом
так как кнопки в едином цвете, отличающийся цвет может не сбить с толку

2024-10-14 10:07 UTC, Kovallll commented on src/components/EditProfileModal/index.tsx
> +    nameText,
сделал

2024-10-14 10:40 UTC, Kovallll commented on src/components/EditProfileModal/index.tsx
> +        dispatch(updateUserData({ ...editData, description: value }))
исправил

2024-10-14 10:40 UTC, Kovallll commented on src/components/EditProfileModal/index.tsx
> +        dispatch(updateUserData({ ...editData, social: value }))
исправил

2024-10-14 10:41 UTC, Kovallll commented on src/constants/dynamicConstants/index.ts
> +import eyeOpen from '@assets/icons/eyeSee.svg'
согласен, назвал defaultValues

2024-10-14 11:33 UTC, Kovallll commented on src/utils/index.tsx
> +
2) сделал, 3) хорошо, добавил типизацию, 4) ну я изменил JSON.parse(JSON.strigify(null)) на JSON.parse("null"), но мне кажется JSON.parse нужно оставить, удобнее вызвать localStorage.getItem(...) , чем постоянно каждый вызов getItem оборачивать в JSON.parse. Из плюсов: переиспользование кода, удобнее читать, из минусов: когда данных нет в localStorage будет делаться лишняя операция по парсингу "null".  Думаю плюсы перекрывают минусы 5) Я читал что такой способ является безопасным и совместимым, иногда при отключении localStorage в window св-во localStorage все равно имеется. 6) ну чтобы не нарушать принцип YAGNI это делать пока не буду, но при написании тестов мне понадобится удалять элементы из localStorage и я там добавил removeItem метод.

2024-10-14 11:45 UTC, Kovallll commented on src/constants/dynamicConstants/index.ts
> +    isLoadingTweet: false,
isSidebarOpen и isTweetModalOpen встечаются в двух разных блоках страницы Sidebar и ProfileMainContent, если бы у меня больше не было страниц, то можно было бы просто вынести состояние в Profile страницу и передать пропсами на 1-2 уровня, но в будущем я добавляю страницу HomePage и UserPage где также есть как основная страница так и sidebar где также будут нужны эти переменные состояния, поэтому они в дальнейшем будут использоваться чаще и нахождение их в глобальным сторе будет оправданным. Я лучше тогда разделю эти переменные на два стейта, loaderState и openedState

2024-10-14 12:00 UTC, Kovallll commented on src/components/Modal/ConfirmModal/index.tsx
> +import { cancelText, checkTitleText } from './config'
согласен, добавил

2024-10-14 12:08 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +                            <Logo src={logo} alt={logoAltText} />
странно, если иконка не загрузилась, то разве черный прямоугольник должен быть, и alt текста нету. У меня такой проблемы не было, не думаю что это проблема с кодом, у тебя такое постоянно или один раз так не подгрузилось?

2024-10-14 17:14 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +                            <Logo src={logo} alt={logoAltText} />
сейчас все хорошо

2024-10-14 17:15 UTC, anyaprystavka requested changes

2024-10-14 17:15 UTC, anyaprystavka commented on src/utils/index.tsx
> +
4) Есть минус у твоего решения. ты парсишь то что не обязательно делать
<img width="203" alt="image" src="https://github.com/user-attachments/assets/3431be06-66d9-4a33-98f9-62f2dece9985">

если доставать несуществующий ключ, то у тебя и так будет null
намного логичнее сделать так
const storageValue = window.localStorage.getItem(key)

if(!storageValue) return storageValue
return JSON.parse(storageValue)

5) В таких случаях лучше сразу при аргументации прикреплять ссылку на источник (в идеале несколько)

6) принимается

2024-10-14 17:52 UTC, Kovallll commented on src/utils/index.tsx
> +
4. согласен, изменил 5. https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#feature-detecting_localstorage, https://stackoverflow.com/questions/16427636/check-if-localstorage-is-available

2024-10-14 18:01 UTC, anyaprystavka approved these changes

2024-10-14 19:03 UTC, merged