Feature/theme
Kovallll/twitter pull request #3
Opened 2024-10-14 19:35 UTC by Kovallll

добавил логику переключения темы, темную тему, сохранения в localStorage ее значения чтобы при обновлении не сбрасывалась. Общие цвета назвал по цветам(blue, gray, green...) а те, которые должны изменяться при переключении темы и относится определенным элементам назвал относительно их.

2024-10-15 19:11 UTC, anyaprystavka requested changes

2024-10-15 19:11 UTC, anyaprystavka commented on src/assets/icons/eyeSeeDark.svg
название переменной было изменено на eyeOpen
а название картинки - нет

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
selector

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/Input/PasswordInput/index.tsx
> +    const eyeIcon = isShowPassword ? hideIcon : showIcon
условие не супер большое
можно не выносить такие моменты

дальше тогда в едином стиле нужно писать

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/Sidebar/index.tsx
> +    const { user } = useAppSelector((state) => state.user)
selector

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/Sidebar/styled.ts
> +            @media (${theme.media.sm}) {
пустые строки

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/Tweet/index.tsx
> +    const moreIcon = getIsLightTheme(theme)
функция getIsLightTheme избыточна
такое сравнение не нужно выноситься отдельно в функцию
не везде нужно все переиспользовать

2024-10-15 19:11 UTC, anyaprystavka commented on src/assets/icons/eyeSlashDark.svg
исходя из темной и светлой темы у тебя есть иконки
которые дублируются, только они разного цвета

тут ты можешь работать с одной и менять fill у них
под такие вещи можно написать функцию по необходимости

то есть тут будет работа со стилизацией

2024-10-15 19:11 UTC, anyaprystavka commented on src/constants/defaultValues/index.ts
> +import notificationDarkIcon from '@assets/icons/notificationDark.svg'
увеличивается вес картинок с общего
стоит работать с одной и менять цвет

2024-10-15 19:11 UTC, anyaprystavka commented on src/styles/theme.ts
> +        textColor: 'black',
не объявлено в HEX

2024-10-15 19:11 UTC, anyaprystavka commented on src/providers/ThemeProvider/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
можно вынести в функцию
(state) => state.user

2024-10-15 19:11 UTC, anyaprystavka commented on src/providers/ThemeProvider/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
это currentTheme используется из redux
так наглядней

2024-10-15 19:11 UTC, anyaprystavka commented on src/providers/ThemeProvider/index.tsx
> +        providerTheme = darkTheme
<ThemeProvider theme={currentTheme === Themes.Dark ? darkTheme : lightTheme}>{children}</ThemeProvider>

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/ToggleThemeButton/index.tsx
>  export const ToggleButton = ({ ...props }) => {
название компонента не соответствует названию папки

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/ToggleThemeButton/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
theme  -> currentTheme

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/ToggleThemeButton/index.tsx
> +    const [isToggle, setIsToggle] = useState(theme === Themes.Dark)
исходят из условия, что ты проверяешь
это больше isDarkTheme

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/ToggleThemeButton/index.tsx
> +    const currentTheme = theme === Themes.Light ? Themes.Dark : Themes.Light
если тема из редакса равна светлой теме, то текущая тема темная?

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/ToggleThemeButton/index.tsx
>      return (
Название компонента связано с кнопкой переключения
а тут Container

2024-10-15 19:11 UTC, anyaprystavka commented on src/assets/icons/eyeSeeDark.svg
с остальными тоже нужно пересмотреть

2024-10-15 19:11 UTC, anyaprystavka commented on src/components/TweetCreator/index.tsx
> +
когда пользователь зашел на какой-то из постов
то если нажать на "Tweet" кнопку
окно открывается модальное, но его не видно
только если перейти на страницу основную - виден
так задумано изначально было?

2024-10-15 19:17 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
поправил

2024-10-15 19:26 UTC, Kovallll commented on src/components/Input/PasswordInput/index.tsx
> +    const eyeIcon = isShowPassword ? hideIcon : showIcon
ну я до этого также выносил такие выражения, поэтому уже в этом проекте буду придерживаться такого стиля, мне так приятнее глазу, в дальнейшем уже такие моменты будут от проекта зависеть

2024-10-15 19:27 UTC, Kovallll commented on src/components/Sidebar/index.tsx
> +    const { user } = useAppSelector((state) => state.user)
поправил

2024-10-15 19:29 UTC, Kovallll commented on src/components/Tweet/index.tsx
> +    const moreIcon = getIsLightTheme(theme)
убрал

2024-10-15 19:30 UTC, Kovallll commented on src/styles/theme.ts
> +        textColor: 'black',
поправил

2024-10-15 19:30 UTC, Kovallll commented on src/providers/ThemeProvider/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
сделал

2024-10-15 19:57 UTC, Kovallll commented on src/providers/ThemeProvider/index.tsx
> +        providerTheme = darkTheme
поправил

2024-10-15 19:57 UTC, Kovallll commented on src/providers/ThemeProvider/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
поправил

2024-10-15 19:58 UTC, Kovallll commented on src/components/ToggleThemeButton/index.tsx
>  export const ToggleButton = ({ ...props }) => {
поправил

2024-10-15 19:58 UTC, Kovallll commented on src/components/ToggleThemeButton/index.tsx
> +    const { theme } = useAppSelector((state) => state.user)
изменил

2024-10-15 19:59 UTC, Kovallll commented on src/components/ToggleThemeButton/index.tsx
> +    const currentTheme = theme === Themes.Light ? Themes.Dark : Themes.Light
не, возможно название немного не верное, назвал changedTheme, т.к. это значение темы, которое будет при изменении

2024-10-15 20:11 UTC, Kovallll commented on src/components/ToggleThemeButton/index.tsx
> +    const [isToggle, setIsToggle] = useState(theme === Themes.Dark)
согласен, что-то странное написал)

2024-10-15 20:17 UTC, Kovallll commented on src/components/ToggleThemeButton/index.tsx
>      return (
исправил

2024-10-15 20:28 UTC, Kovallll commented on src/components/TweetCreator/index.tsx
> +
не, убрал эту кнопу при переходе на страницу отличную от profile

2024-10-15 20:57 UTC, Kovallll commented on src/components/Sidebar/styled.ts
> +            @media (${theme.media.sm}) {
исправил

2024-10-15 20:58 UTC, Kovallll commented on src/assets/icons/eyeSeeDark.svg
поправил

2024-10-16 07:27 UTC, Kovallll commented on src/assets/icons/eyeSlashDark.svg
добавил vite-plugin-svgr и иконки теперь как компоненты и передаю в fill цвет нужный

2024-10-16 07:28 UTC, Kovallll commented on src/constants/defaultValues/index.ts
> +import notificationDarkIcon from '@assets/icons/notificationDark.svg'
удалил лишние иконки

2024-10-16 10:36 UTC, anyaprystavka approved these changes

2024-10-16 11:51 UTC, merged