Feature/home&account
Kovallll/twitter pull request #4
Opened 2024-10-16 14:24 UTC by Kovallll

Добавил страницу Home с отображением сортированных твитов по дате поста, добавил поиск по юзерам, также добавил страницу пользователя, при клике на картинку или имя пользователя открывается страница, где уже нельзя изменить данные профиля и  создать, удалить твит. Таски: https://app.clickup.com/t/86965dmmu, https://app.clickup.com/t/8695xxaw3, Коммит: 3320df7d071f5d6af95bbfe4079f51af6a9f4c29

2024-10-17 09:34 UTC, anyaprystavka requested changes

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/AccountCard/index.tsx
> +    account,
memo?

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/AccountCard/styled.ts
> +export const AccountName = styled.p`
AccountName  -> UserName

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/AccountCard/styled.ts
> +export const AccountSocial = styled.p`
AccountSocial  -> UserSocial

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/AccountCard/styled.ts
> +export const AccountAvatar = styled(ProfileIcon)`
AccountAvatar  -> UserAvatar

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/AccountCard/index.tsx
> +    withButton = true,
какой кнопкой?
withFollowButton

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +                    title={title}
опциональный параметр
нет дефолтного значения

2024-10-17 09:34 UTC, anyaprystavka commented on src/components/TwitterUsersContent/TwitterAccountsBoard/index.tsx
> +                        <AccountCard account={account} />
key

2024-10-17 09:34 UTC, anyaprystavka commented on src/constants/defaultValues/index.ts
> +    User = `${userPath}/:userId`,
очень файл начал разростаться с константами

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Home/AllTweets/index.tsx
> +                <Tweet data={{ tweetData: tweet, account: account }} />
key

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Home/index.tsx
> +    const allAccounts = [...accounts, user]
пересчет allAccounts при ререндере

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Profile/ProfileMainContent/ProfileInfo/Loader/index.tsx
> +import { editText } from '../../config'
алиасы

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Profile/ProfileMainContent/ProfileInfo/index.tsx
> +    const isUserTweet = currentuUser.userId === user.userId
просится деструктуризация
дублируются значения

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Profile/ProfileMainContent/ProfileTweets/index.tsx
> +                    data={{ tweetData: data, account: user }}
key

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Profile/index.tsx
> +    const { user } = useAppSelector(userSelector)
чтобы не использовать props-drilling
значение можно взять из стора в самих компонентах, где используется значение

2024-10-17 09:34 UTC, anyaprystavka commented on src/pages/Home/index.tsx
> +    const { accounts } = useAppSelector(totalSelector)
договорились об infinity scroll для подгрузки постов

2024-10-17 10:05 UTC, Kovallll commented on src/components/AccountCard/index.tsx
> +    account,
добавил

2024-10-17 10:09 UTC, Kovallll commented on src/components/AccountCard/index.tsx
> +    withButton = true,
поправил

2024-10-17 10:12 UTC, Kovallll commented on src/components/Header/index.tsx
> +                    title={title}
там чуть дальше в HeaderContent используется проверка, если есть title, то одна визуализация, если нет, то другая, поэтому дефолтное значение не нужно

2024-10-17 10:14 UTC, Kovallll commented on src/components/TwitterUsersContent/TwitterAccountsBoard/index.tsx
> +                        <AccountCard account={account} />
поправил

2024-10-17 10:14 UTC, Kovallll commented on src/pages/Home/AllTweets/index.tsx
> +                <Tweet data={{ tweetData: tweet, account: account }} />
поправил

2024-10-17 10:17 UTC, Kovallll commented on src/components/AccountCard/styled.ts
> +export const AccountName = styled.p`
тут в приложении названиями account и user я отделяю две сущности, user - конкретно мой аккаунт и соответствующие ему отображения, а account - аккаунты других пользователей и также их отображения, поэтому тут я и называл так

2024-10-17 10:17 UTC, Kovallll commented on src/components/AccountCard/styled.ts
> +export const AccountSocial = styled.p`
тут в приложении названиями account и user я отделяю две сущности, user - конкретно мой аккаунт и соответствующие ему отображения, а account - аккаунты других пользователей и также их отображения, поэтому тут я и называл так

2024-10-17 10:18 UTC, Kovallll commented on src/components/AccountCard/styled.ts
> +export const AccountAvatar = styled(ProfileIcon)`
тут в приложении названиями account и user я отделяю две сущности, user - конкретно мой аккаунт и соответствующие ему отображения, а account - аккаунты других пользователей и также их отображения, поэтому тут я и называл так

2024-10-17 10:21 UTC, Kovallll commented on src/constants/defaultValues/index.ts
> +    User = `${userPath}/:userId`,
перенес все что связанно с sidebar в папку sidebarValues

2024-10-17 10:21 UTC, Kovallll commented on src/pages/Home/index.tsx
> +    const allAccounts = [...accounts, user]
поправил

2024-10-17 10:25 UTC, Kovallll commented on src/pages/Profile/ProfileMainContent/ProfileInfo/Loader/index.tsx
> +import { editText } from '../../config'
перенес все что брал из внешнего конфига в конфиг этой папки

2024-10-17 10:28 UTC, Kovallll commented on src/pages/Profile/ProfileMainContent/ProfileInfo/index.tsx
> +    const isUserTweet = currentuUser.userId === user.userId
согласен, поправил

2024-10-17 10:28 UTC, Kovallll commented on src/pages/Profile/ProfileMainContent/ProfileTweets/index.tsx
> +                    data={{ tweetData: data, account: user }}
поправил

2024-10-17 17:42 UTC, Kovallll commented on src/pages/Home/index.tsx
> +    const { accounts } = useAppSelector(totalSelector)
сделал

2024-10-17 17:43 UTC, Kovallll commented on src/pages/Profile/index.tsx
> +    const { user } = useAppSelector(userSelector)
поправил

2024-10-17 17:44 UTC, Kovallll commented on src/pages/Profile/ProfileMainContent/ProfileTweets/index.tsx
> +                    data={{ tweetData: data, account: user }}
добавил

2024-10-18 07:19 UTC, anyaprystavka requested changes

2024-10-18 07:19 UTC, anyaprystavka commented on src/pages/Home/AllTweets/index.tsx
> +    useEffect(() => {
кастомный хук

2024-10-18 07:19 UTC, anyaprystavka commented on src/pages/Home/AllTweets/index.tsx
> +        const observer = new IntersectionObserver((entries) => {
работа отображения твитов некорректная

случаи, при которых проверяют подгрузку:
1) после перезагрузки страницы
2) при переходе на другую страницу и возврат на главную
3) при переходе н а другого пользователя и возврате на главную 
 
и первом и втором  случаях - подгрузка твитов происходит некорректно, отображается 4 поста, при скроллинге к последнему посту ничего не происходит,  в третьем случае их больше

2024-10-18 07:19 UTC, anyaprystavka commented on src/pages/Profile/index.tsx
> +    const { user } = useAppSelector(userSelector)
код остался тем же
<img width="638" alt="image" src="https://github.com/user-attachments/assets/ed196ece-ec9b-4efa-a708-b56d256fd208">

2024-10-18 07:19 UTC, anyaprystavka commented on src/components/AccountCard/styled.ts
> +export const AccountName = styled.p`
обсудили другой нейминг

Account конкретно в этом случае можно сделать User 
 в InitializerUserData accounts можно переименовать как  users, а user - currentUser

2024-10-18 07:19 UTC, anyaprystavka commented on src/components/AccountCard/styled.ts
> +export const AccountSocial = styled.p`
обсудили другой нейминг

2024-10-18 07:19 UTC, anyaprystavka commented on src/components/AccountCard/styled.ts
> +export const AccountAvatar = styled(ProfileIcon)`
обсудили другой неймиг

2024-10-18 08:27 UTC, Kovallll commented on src/pages/Home/AllTweets/index.tsx
> +    useEffect(() => {
добавил

2024-10-18 08:31 UTC, Kovallll commented on src/pages/Home/AllTweets/index.tsx
> +        const observer = new IntersectionObserver((entries) => {
если постов меньше одной порции(10 постов), то ничего не произойдет, если больше, то будет подгружаться, был баг когда переходишь куда-то, потом назад возвращаешься, то подгружаются предыдущие посты повторно, это пофиксил, просто состояние сохранялось постов, а состояние страниц нет и поэтому начинало с нуля подгружать, теперь если мы , допустим, до 100 поста прогрузим, перейдем на другую страницу и вернемся, то те 100 постов останутся а дальше уже будут новые подгружаться

2024-10-18 08:31 UTC, Kovallll commented on src/components/AccountCard/styled.ts
> +export const AccountAvatar = styled(ProfileIcon)`
переименовал

2024-10-18 08:31 UTC, Kovallll commented on src/components/AccountCard/styled.ts
> +export const AccountSocial = styled.p`
переименовал

2024-10-18 08:31 UTC, Kovallll commented on src/components/AccountCard/styled.ts
> +export const AccountName = styled.p`
переименовал

2024-10-18 09:42 UTC, Kovallll commented on src/pages/Profile/index.tsx
> +    const { user } = useAppSelector(userSelector)
поправил

2024-10-18 12:52 UTC, anyaprystavka approved these changes

2024-10-18 12:53 UTC, merged